session_name: website
start_directory: ./ # load session relative to config location (project root).
before_script: pipenv install --dev --skip-lock
windows:
- window_name: website
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./
  shell_command_before:
    - '[ -d `pipenv --venv` ] && source `pipenv --venv`/bin/activate && reset'
  panes:
  - focus: true
  - pane
  - make serve
  - make watch
