[tool.poetry]
name = "git-pull-website"
version = "0.3.0"
description = "git-pull website"

license = "All Rights Reserved."

authors = [
    "Tony Narlock <tony@git-pull.com>"
]

readme = 'README.rst'

homepage = "https://www.git-pull.com"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/git-pull/website/issues"
Repository = "https://github.com/git-pull/website"

[tool.poetry.dependencies]
python = "^3.7"

### Docs ###
sphinx = "*"
alagitpull = "^0.1.0"
sphinx-autodoc-typehints = "~1.17.0"
myst_parser = "~0.17.0"
sphinx-autobuild = "^2021.3.14"

[tool.poetry.dev-dependencies]
### Format ###
black = "*"
isort = "*"

### Lint ###
flake8 = "*"

[tool.poetry.extras]
docs = ["sphinx", "alagitpull", "myst_parser", "sphinx-autodoc-typehints", "sphinx-autobuild"]
format = ["black", "isort"]
lint = ["flake8"]
