[tool.poetry]
name = "git-pull-website"
version = "0.3.0"
description = "git-pull website"

license = "All Rights Reserved."

authors = [
  "Tony Narlock <tony@git-pull.com>",
]

readme = 'README.rst'

homepage = "https://www.git-pull.com"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/git-pull/website/issues"
Repository = "https://github.com/git-pull/website"

[tool.poetry.dependencies]
python = "^3.10"

### Docs ###
sphinx = "*"
furo = "*"
sphinx-autobuild = "*"
sphinx-click = "*"
sphinx-inline-tabs = { version = "*", python = "^3.7" }
sphinxext-opengraph = "*"
sphinx-copybutton = "*"
sphinxext-rediraffe = "*"
myst_parser = "*"

[tool.poetry.dev-dependencies]
### Docs ###
sphinx-autobuild = "*"

### Format ###
black = "*"
isort = "*"

### Lint ###
flake8 = "*"

[tool.poetry.extras]
docs = [
  "sphinx",
  "sphinx-autobuild",
  "sphinx-copybutton",
  "sphinxext-opengraph",
  "sphinx-inline-tabs",
  "sphinxext-rediraffe",
  "myst_parser",
  "furo",
]
format = ["black", "isort"]
lint = ["flake8"]
