[tool.poetry]
name = "git-pull-website"
version = "0.3.0"
description = "git-pull website"

license = "All Rights Reserved."

authors = [
    "Tony Narlock <tony@git-pull.com>"
]

readme = 'README.rst'

homepage = "https://www.git-pull.com"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/git-pull/website/issues"
Repository = "https://github.com/git-pull/website"

[tool.poetry.dependencies]
python = "^3.6"

### Docs ###
sphinx = "*"
alagitpull = "^0.1.0"
sphinx-autodoc-typehints = "^1.12.0"
myst_parser = "^0.15.0"

[tool.poetry.dev-dependencies]
### Format ###
black = {version="==21.6b0", python="^3.6.2"}
isort = "*"

### Lint ###
flake8 = "*"

[tool.poetry.extras]
docs = ["sphinx", "alagitpull", "myst_parser", "sphinx-autodoc-typehints"]
format = ["black", "isort"]
lint = ["flake8"]

[tool.black]
skip-string-normalization = true
include = '\.pyi?$'
